name: "gatsby deploy"

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install Project Dependencies
        run: npm ci
      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli gh-pages
      - name: Setup git config
        run: |
          git config user.name "${{ secrets.USERNAME }}"
          git config user.email "${{ secrets.EMAIL }}"
      - name: Deploy
        run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}